name: Web Request Cronjob

on:
  schedule:
    - cron: '*/5 * * * *'  # Se ejecuta cada 5 minutos
  workflow_dispatch:  # Permite ejecución manual opcional

jobs:
  request-job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: |
          curl -X GET "https://fast-api-crud-44cz.onrender.com/items"
